# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4aab684fc6c4cf0084322d59a5906bb02d4a515508eba70d16221fec75591e18dc79ee296ef3e35ee89f921897aabd0580aea8ce454e048378a44e9522abacd

test:
  secret_key_base: 15d83d62d012f9fe61afa74aedc445b954b4abcca9bee6c1718a3c531fc9933da70ed9dab31e12a3c6bc76a6f5f7a7a6b8d180d35ca26cf7413b91c3c7c94368

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
